# Flask Dockerfile
FROM python:3.11-slim

WORKDIR /app

# 필요한 패키지 설치
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# 앱 코드 복사
COPY . .

# Flask 실행
CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
